##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## make
##

################# Rules ###################
all:
	@make --no-print-directory -C snake re

clean:
	@make --no-print-directory -C snake clean

fclean: clean
	@make --no-print-directory -C snake fclean

re: fclean all

###########################################